services:
  bot-api-service:
    image: bot-api-service:dev
    container_name: bot-api-service-dev
    build:
      context: ./bot_service
      dockerfile: ./dockerfiles/api.Dockerfile
    env_file:
        - ./bot_service/src/backend/etc/.env
    # volumes:
      # - ./common:/app/common
    healthcheck:
      test: curl --fail http://localhost:8081/v1/api/health || exit 1
      interval: 40s
      timeout: 30s
      retries: 3
      start_period: 60s
    ports:
      - 8085:8081
    networks:
      - shared_network
      - llm-network
    dns:
      - 8.8.8.8
    restart: "unless-stopped"

  bot-ui-service:
    image: bot-ui-service:dev
    container_name: bot-ui-service-dev
    build:
      context: ./bot_service
      dockerfile: ./dockerfiles/ui.Dockerfile
    env_file:
      - ./bot_service/src/frontend/etc/.env
    # volumes:
    #   - ./common:/app/common
    healthcheck:
      test: curl --fail http://localhost:3000 || exit 1
      interval: 40s
      timeout: 30s
      retries: 3
      start_period: 60s
    ports:
      - "3001:3000"
    networks:
      - shared_network
    dns:
      - 8.8.8.8
    restart: "unless-stopped"
    command: ["npm", "start"]
    depends_on:
      - bot-api-service

networks:
  shared_network:
    external: true
  llm-network:
    external: true
