site_name: Fantastics Fiesta Docs
theme:
  name: material
  features:
    - navigation.path
    - toc.follow
    - navigation.tracking
    - content.code.copy
    - content.code.select
    - content.code.select
  icon:
    repo: fontawesome/brands/github
  palette:

    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode


repo_url: https://github.com/newtuple/fantastic-fiesta
repo_name: fantastic-fiesta


markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences


plugins:
    - search
