apiVersion: v1
kind: ConfigMap
metadata:
  name: ama-metrics-settings-configmap
  namespace: kube-system

data:
  schema-version:
    {{ .Values.config.schemaVersion }}
  config-version:
    {{ .Values.config.configVersion }}
  prometheus-collector-settings: |-
    cluster_alias = "{{ .Values.config.prometheusCollectorSettings.clusterAlias }}"
  default-scrape-settings-enabled: |-
    kubelet = {{ .Values.config.defaultScrapeSettingsEnabled.kubelet }}
    coredns = {{ .Values.config.defaultScrapeSettingsEnabled.coredns }}
    cadvisor = {{ .Values.config.defaultScrapeSettingsEnabled.cadvisor }}
    kubeproxy = {{ .Values.config.defaultScrapeSettingsEnabled.kubeproxy }}
    apiserver = {{ .Values.config.defaultScrapeSettingsEnabled.apiserver }}
    kubestate = {{ .Values.config.defaultScrapeSettingsEnabled.kubestate }}
    nodeexporter = {{ .Values.config.defaultScrapeSettingsEnabled.nodeexporter }}
    windowsexporter = {{ .Values.config.defaultScrapeSettingsEnabled.windowsexporter }}
    windowskubeproxy = {{ .Values.config.defaultScrapeSettingsEnabled.windowskubeproxy }}
    kappiebasic = {{ .Values.config.defaultScrapeSettingsEnabled.kappiebasic }}
    networkobservabilityRetina = {{ .Values.config.defaultScrapeSettingsEnabled.networkobservabilityRetina }}
    networkobservabilityHubble = {{ .Values.config.defaultScrapeSettingsEnabled.networkobservabilityHubble }}
    networkobservabilityCilium = {{ .Values.config.defaultScrapeSettingsEnabled.networkobservabilityCilium }}
    prometheuscollectorhealth = {{ .Values.config.defaultScrapeSettingsEnabled.prometheuscollectorhealth }}
    controlplane-apiserver = {{ .Values.config.defaultScrapeSettingsEnabled.controlplaneApiserver }}
    controlplane-cluster-autoscaler = {{ .Values.config.defaultScrapeSettingsEnabled.controlplaneClusterAutoscaler }}
    controlplane-kube-scheduler = {{ .Values.config.defaultScrapeSettingsEnabled.controlplaneKubeScheduler }}
    controlplane-kube-controller-manager = {{ .Values.config.defaultScrapeSettingsEnabled.controlplaneKubeControllerManager }}
    controlplane-etcd = {{ .Values.config.defaultScrapeSettingsEnabled.controlplaneEtcd }}
  pod-annotation-based-scraping: |-
    podannotationnamespaceregex = "{{ .Values.config.podAnnotationBasedScraping }}"
  default-targets-metrics-keep-list: |-
    kubelet = "{{ .Values.config.defaultTargetsMetricsKeepList.kubelet }}"
    coredns = "{{ .Values.config.defaultTargetsMetricsKeepList.coredns }}"
    cadvisor = "{{ .Values.config.defaultTargetsMetricsKeepList.cadvisor }}"
    kubeproxy = "{{ .Values.config.defaultTargetsMetricsKeepList.kubeproxy }}"
    apiserver = "{{ .Values.config.defaultTargetsMetricsKeepList.apiserver }}"
    kubestate = "{{ .Values.config.defaultTargetsMetricsKeepList.kubestate }}"
    nodeexporter = "{{ .Values.config.defaultTargetsMetricsKeepList.nodeexporter }}"
    windowsexporter = "{{ .Values.config.defaultTargetsMetricsKeepList.windowsexporter }}"
    windowskubeproxy = "{{ .Values.config.defaultTargetsMetricsKeepList.windowskubeproxy }}"
    podannotations = "{{ .Values.config.defaultTargetsMetricsKeepList.podannotations }}"
    kappiebasic = "{{ .Values.config.defaultTargetsMetricsKeepList.kappiebasic }}"
    networkobservabilityRetina = "{{ .Values.config.defaultTargetsMetricsKeepList.networkobservabilityRetina }}"
    networkobservabilityHubble = "{{ .Values.config.defaultTargetsMetricsKeepList.networkobservabilityHubble }}"
    networkobservabilityCilium = "{{ .Values.config.defaultTargetsMetricsKeepList.networkobservabilityCilium }}"
    controlplane-apiserver = "{{ .Values.config.defaultTargetsMetricsKeepList.controlplaneApiserver }}"
    controlplane-cluster-autoscaler = "{{ .Values.config.defaultTargetsMetricsKeepList.controlplaneClusterAutoscaler }}"
    controlplane-kube-scheduler = "{{ .Values.config.defaultTargetsMetricsKeepList.controlplaneKubeScheduler }}"
    controlplane-kube-controller-manager = "{{ .Values.config.defaultTargetsMetricsKeepList.controlplaneKubeControllerManager }}"
    controlplane-etcd = "{{ .Values.config.defaultTargetsMetricsKeepList.controlplaneEtcd }}"
    minimalingestionprofile = {{ .Values.config.defaultTargetsMetricsKeepList.minimalingestionprofile }}
  default-targets-scrape-interval-settings: |-
    kubelet = "{{ .Values.config.defaultTargetsScrapeIntervalSettings.kubelet }}"
    coredns = "{{ .Values.config.defaultTargetsScrapeIntervalSettings.coredns }}"
    cadvisor = "{{ .Values.config.defaultTargetsScrapeIntervalSettings.cadvisor }}"
    kubeproxy = "{{ .Values.config.defaultTargetsScrapeIntervalSettings.kubeproxy }}"
    apiserver = "{{ .Values.config.defaultTargetsScrapeIntervalSettings.apiserver }}"
    kubestate = "{{ .Values.config.defaultTargetsScrapeIntervalSettings.kubestate }}"
    nodeexporter = "{{ .Values.config.defaultTargetsScrapeIntervalSettings.nodeexporter }}"
    windowsexporter = "{{ .Values.config.defaultTargetsScrapeIntervalSettings.windowsexporter }}"
    windowskubeproxy = "{{ .Values.config.defaultTargetsScrapeIntervalSettings.windowskubeproxy }}"
    kappiebasic = "{{ .Values.config.defaultTargetsScrapeIntervalSettings.kappiebasic }}"
    networkobservabilityRetina = "{{ .Values.config.defaultTargetsScrapeIntervalSettings.networkobservabilityRetina }}"
    networkobservabilityHubble = "{{ .Values.config.defaultTargetsScrapeIntervalSettings.networkobservabilityHubble }}"
    networkobservabilityCilium = "{{ .Values.config.defaultTargetsScrapeIntervalSettings.networkobservabilityCilium }}"
    prometheuscollectorhealth = "{{ .Values.config.defaultTargetsScrapeIntervalSettings.prometheuscollectorhealth }}"
    podannotations = "{{ .Values.config.defaultTargetsScrapeIntervalSettings.podannotations }}"
  debug-mode: |-
    enabled = {{ .Values.config.debugMode.enabled }}
