{{- range .Values.services }}
{{- if .enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .name }}-deployment
  labels:
    app: {{ .name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .name }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2        # Allow 1 extra pod during updates
      maxUnavailable: 0  # Allow 0 pods to be unavailable during updates
  template:
    metadata:
      labels:
        app: {{ .name }}
      {{- if .metrics.enabled }}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: {{ .metrics.scrapePath | quote }}
        prometheus.io/port: {{ .port | quote }}
      {{- end }}
      {{- if .hpa.enabled }}
        hpa.autoscaling.k8s.io/enabled: "true"
      {{- end }}
    spec:
      containers:
      - name: {{ .name }}
        image: {{ .imageName }}:{{ $.Values.releases.version }}
        imagePullPolicy: Always
        env:
        - name: PORT
          value: {{ .port | quote }}
        {{- if .env }}
        {{- range $key, $value := .env }}
        - name: {{ $key }}
          value: {{ $value | quote }}
        {{- end }}
        {{- end }}
        ports:
        - containerPort: {{ .port }}
        resources:
          limits:
            cpu: {{ .resources.limits.cpu }}
            memory: {{ .resources.limits.memory }}
          requests:
            cpu: {{ .resources.requests.cpu }}
            memory: {{ .resources.requests.memory }}
        livenessProbe:
          httpGet:
            path: {{ .livenessProbePath | quote }}
            port: {{ .port }}
          initialDelaySeconds: {{ .livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .livenessProbe.periodSeconds }}
          timeoutSeconds: {{ .livenessProbe.timeoutSeconds }}
        readinessProbe:
          httpGet:
            path: {{ .readinessProbePath | quote }}
            port: {{ .port }}
          initialDelaySeconds: {{ .readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .readinessProbe.periodSeconds }}
          timeoutSeconds: {{ .readinessProbe.timeoutSeconds }}
      {{- if .tolerations.enabled }}
      tolerations:
        - key: {{ .tolerations.key | quote }}
          operator: {{ .tolerations.operator | quote }}
      {{- end }}
---
{{- end }}
{{- end }}